version: "3.9"

services:
  keycloak:
    build: ./keycloak/config
    container_name: authentication
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - 8081:8080
    command: "start-dev --hostname-strict=false"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - db  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGUSER: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5     

